/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/happy_halloween.glb --transform
Author: jeremiahogreen06 (https://sketchfab.com/jeremiahogreen06)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/happy-halloween-7bd78d318d134d6e9588f9f9af6748ad
Title: happy_halloween
*/

import React, { useRef } from "react";
import { Center, useGLTF } from "@react-three/drei";
import Halloween from "./Halloween";
import { Color } from "three";

export function Model(props) {
	const { nodes, materials } = useGLTF(
		"/models/happy_halloween-transformed.glb",
	);

	return (
		<Center position={[0, 0.5, -1]}>
			<group {...props} dispose={null}>
				<group rotation={[-Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.Object_7.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_9.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_11.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_13.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_15.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_17.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_19.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_21.geometry}
						material={materials.material_0}
					/>
				</group>
			</group>
		</Center>
	);
}

export function Pumpkin(props) {
	const { nodes, materials } = useGLTF(
		"/models/happy_halloween-transformed.glb",
	);

	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Object_9.geometry}
					material={materials.material_0}
				/>
			</group>
		</group>
	);
}

export function InfectedModel(props) {
	const { nodes, materials } = useGLTF(
		"/models/happy_halloween-transformed.glb",
	);
	return (
		<Center position={[0, 0, -1]}>
			<group {...props} dispose={null}>
				<group rotation={[-Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.Object_7.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_9.geometry}
						material={materials.material_0}
					/>
					{/* <mesh
						geometry={nodes.Object_11.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_13.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_15.geometry}
						material={materials.material_0}
					/> */}
					<mesh
						geometry={nodes.Object_17.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_19.geometry}
						material={materials.material_0}
					/>
					<mesh
						geometry={nodes.Object_21.geometry}
						material={materials.material_0}
					/>
				</group>
			</group>
		</Center>
	);
}

useGLTF.preload("/models/happy_halloween-transformed.glb");
